services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
  ecommerce_app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./ecommerce/db.sqlite3:/app/ecommerce/db.sqlite3
  ecommerce_app_celery_worker:
    build: .
    command: celery -A ecommerce worker --loglevel INFO
    depends_on:
      - redis
      - ecommerce_app
    volumes:
      - ./ecommerce/db.sqlite3:/app/ecommerce/db.sqlite3